In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [23]:
np.apply_along_axis(lambda x : pow(2, x) / x, 0, np.arange(1, 21))

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [30]:
np.sum(np.apply_along_axis(lambda x : pow(0.1, 3*x) * pow(0.2, 4 * x), 0, np.arange(0, 6)), axis = 0)

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [81]:
np.apply_along_axis( lambda x : (x + x / 8).astype('int') % 2, 0, np.arange(0, 64)).reshape((8, 8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [102]:
X = np.random.random((5, 2))

def foo(x, y):
    if (x > 0 and y >= 0):
        return np.arctan(y / x)
    if (x > 0 and y < 0):
        return np.arctan(y / x) + 2 * np.pi
    if (x < 0):
        return np.arctan(y / x) + np.pi
    if (x  == 0 and y > 0):
        return np.pi / 2
    if (x == 0 and y < 0):
        return np.pi * 3 / 2
    if (x == 0 and y == 0):
        return None



np.apply_along_axis(lambda x: np.array([np.sqrt(x[0]**2 + x[1] ** 2), foo(x[0], x[1])]) ,1, X)

array([[ 0.95030765,  0.59211316],
       [ 0.73268955,  0.78480864],
       [ 0.96841725,  0.8754769 ],
       [ 0.12585401,  1.15582377],
       [ 1.00278852,  0.95586135]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [108]:
X = np.random.random((10, 10))

res = np.argmax(X)
print( int(res / 10), res % 10 )

3 5


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [118]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

np.argmin(np.apply_along_axis(lambda x : np.sqrt( (x[0] - y[0, 0])** 2 + (x[1] - y[0, 1])**2 ), 1, X))

2

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [125]:
def func(x):
    if (x < 0):
        return x**2 + 2 * x + 6
    elif ( x <= 2):
        return x + 6
    else:
        return x**2 + 4 * x - 4

f  = np.vectorize(func)

In [126]:
f(np.linspace(-3, 3, 100))

array([  9.        ,   8.76124885,   8.52984389,   8.30578512,
         8.08907254,   7.87970615,   7.67768595,   7.48301194,
         7.29568411,   7.11570248,   6.94306703,   6.77777778,
         6.61983471,   6.46923783,   6.32598714,   6.19008264,
         6.06152433,   5.94031221,   5.82644628,   5.71992654,
         5.62075298,   5.52892562,   5.44444444,   5.36730946,
         5.29752066,   5.23507805,   5.17998163,   5.1322314 ,
         5.09182736,   5.05876951,   5.03305785,   5.01469238,
         5.00367309,   5.        ,   5.00367309,   5.01469238,
         5.03305785,   5.05876951,   5.09182736,   5.1322314 ,
         5.17998163,   5.23507805,   5.29752066,   5.36730946,
         5.44444444,   5.52892562,   5.62075298,   5.71992654,
         5.82644628,   5.94031221,   6.03030303,   6.09090909,
         6.15151515,   6.21212121,   6.27272727,   6.33333333,
         6.39393939,   6.45454545,   6.51515152,   6.57575758,
         6.63636364,   6.6969697 ,   6.75757576,   6.81

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [133]:
X = np.random.random((10, 10))

X = X - np.apply_along_axis(np.mean, 0, X).T

np.apply_along_axis(np.mean, 0, X).T

array([  3.33066907e-17,  -7.77156117e-17,  -2.22044605e-17,
         7.77156117e-17,   5.55111512e-17,  -3.33066907e-17,
         4.44089210e-17,   2.22044605e-17,   2.22044605e-17,
         2.22044605e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [136]:
X = np.random.normal(loc=5, scale=2., size=1000)

print("srednee", np.mean(X))
print('dispersiya', np.mean(np.power(X, 2)) -np.mean(X)**2)

srednee 5.0920778433
dispersiya 4.01630548533


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [137]:
np.apply_along_axis( lambda x : (x + x / 5).astype('int') % 5, 0, np.arange(0, 25)).reshape((5, 5))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)